### ISSUE TITLE
Will you please reform it to a python implementation ?

### ISSUE THREAD

**Issue by skywind3000** [mattn/vimtweak#1]
Great plugin, thanks

GVim has 32 or 64 bits version and a DLL is hard to use today, 
most of windows gvim users will install python interpreter to run YouCompleteMe today.

and python could access any win32 apis with ctypes via kernel32.dll and user32.dll.
So would you please to write a python version of vimtweek to get rid of the DLL, and only a .vim file ?

**Comment by mattn** [comment]
added 32/64 binary both. and added small script.

**Comment by skywind3000** [comment]
just reference your code and write a python version:
[vimtweak2.vim](https://gist.github.com/skywind3000/8eb41acd9d5175715694c765f92fa667) 

just waste of time...
